### PR TITLE
Issue3

### PR DESCRIPTION
**Pull request by tammoterhark**
Deleted border around the smileys

### CODE REVIEW

**Comment by tpartner** [comment]
Hi Tammo, thanks for your input. 

Unfortunately, I'm not a fan of the gray monochrome imposed by a saturation of 0. I prefer the icons to have some indication coloring in their un-checked state.

I suppose, if more contrast is needed for the checked state, I could tweak the background colours.

**Comment by tammoterhark** [comment]
You could also have coloration on saturation 0.3 or something like that. I just wanted the hovering and active state to be more clear. 

See my addition as an advise, not as something absolute...

**Comment by tpartner** [comment]
Sure, thanks but I still like the colours. :)

I'm not overly concerned with the hover state as it is not a factor on mobile devices anyway.

**Comment by tammoterhark** [comment]
You are right. Do with it what you think is OK.

Op do 2 mei 2019 om 15:36 schreef Tony Partner <notifications@github.com>:

**Pull request closed without merging**
